version: '3.8'

services:
  claude-oauth-api:
    build: .
    container_name: claude-oauth-api
    ports:
      - "8000:8000"
    environment:
      - API_KEY=${API_KEY:-your-secure-api-key-here}
      - CLAUDE_EMAIL=${CLAUDE_EMAIL}
      - PYTHONUNBUFFERED=1
    volumes:
      - ./logs:/app/logs
      - playwright-data:/home/appuser/.cache/ms-playwright
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - claude-network

  ngrok:
    image: ngrok/ngrok:latest
    container_name: claude-oauth-ngrok
    command: http claude-oauth-api:8000 --authtoken=${NGROK_AUTHTOKEN}
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"  # Ngrok web interface
    depends_on:
      - claude-oauth-api
    networks:
      - claude-network
    restart: unless-stopped

volumes:
  playwright-data:

networks:
  claude-network:
    driver: bridge
